# -*- coding: utf-8 -*-
"""fake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1VvQh8kUW8WlFTDQMIWTwEloBAsfTar
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


urls = [
    "https://raw.githubusercontent.com/docketrun/Detecting-Fake-News-with-Scikit-Learn/master/fake_or_real_news.csv",
    "https://raw.githubusercontent.com/lutzhamel/fake-news/master/data/fake_or_real_news.csv"
]


data = None

for url in urls:
    try:
        data = pd.read_csv(url)
        print("Loaded dataset from:")
        print(url)
        break
    except Exception as e:
        last_error = e

if data is None:
    raise RuntimeError(f"Could not load dataset from any source. Last error: {last_error}")


print("\nColumns:")
print(data.columns.tolist())

print("\nPreview:")
print(data.head())


possible_text_columns = ["text", "statement", "content", "article", "news"]
possible_label_columns = ["label", "class", "target", "category", "is_fake"]


text_col = None
label_col = None


for col in possible_text_columns:
    if col in data.columns:
        text_col = col
        break


for col in possible_label_columns:
    if col in data.columns:
        label_col = col
        break


if text_col is None or label_col is None:
    raise ValueError("Could not detect required text and label columns in the dataset.")


data = data[[text_col, label_col]].dropna().copy()

data[text_col] = data[text_col].astype(str)
data[label_col] = data[label_col].astype(str).str.strip().str.lower()


if data[label_col].nunique() > 2:
    unique_labels = sorted(data[label_col].unique().tolist())
    label_map = {unique_labels[0]: 0, unique_labels[1]: 1}
    data[label_col] = data[label_col].map(label_map)
else:
    if set(data[label_col].unique()).issubset({"fake", "real"}):
        data[label_col] = data[label_col].map({"fake": 0, "real": 1})
    elif set(data[label_col].unique()).issubset({"0", "1"}):
        data[label_col] = data[label_col].astype(int)
    else:
        values = sorted(data[label_col].unique().tolist())
        mapping = {values[0]: 0, values[1]: 1}
        data[label_col] = data[label_col].map(mapping)


data[label_col] = data[label_col].astype(int)


X = data[text_col]
y = data[label_col]


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


vectorizer = TfidfVectorizer(
    stop_words="english",
    max_df=0.7,
    max_features=20000
)


X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


model = PassiveAggressiveClassifier(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_tfidf, y_train)


predictions = model.predict(X_test_tfidf)


accuracy = accuracy_score(y_test, predictions)

print("\nAccuracy:")
print(accuracy)

print("\nClassification Report:")
print(classification_report(y_test, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))


sample_news = [
    "Scientists confirm water has been detected on Mars after a new mission.",
    "Government officials secretly admit aliens control the weather from underground bases."
]

sample_vectors = vectorizer.transform(sample_news)
sample_predictions = model.predict(sample_vectors)


print("\nFake News Detection Results:")

for news, prediction in zip(sample_news, sample_predictions):
    result = "Real News" if prediction == 1 else "Fake News"
    print("\nText:")
    print(news)
    print("Prediction:")
    print(result)