# -*- coding: utf-8 -*-
"""lestem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer


nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')


text = """
The boys were running faster than the girls and were enjoying the games happily.
"""


tokens = word_tokenize(text.lower())


print("Tokenized Words:\n")

print(tokens)


stemmer = PorterStemmer()

stemmed_words = [stemmer.stem(word) for word in tokens]


print("\nStemmed Words:\n")

print(stemmed_words)


lemmatizer = WordNetLemmatizer()

lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]


print("\nLemmatized Words:\n")

print(lemmatized_words)