# -*- coding: utf-8 -*-
"""naive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from datasets import load_dataset


dataset = load_dataset("imdb")


train_data = dataset["train"].to_pandas()

test_data = dataset["test"].to_pandas()


print("Training Dataset:\n")

print(train_data.head())


X_train = train_data["text"]

y_train = train_data["label"]


X_test = test_data["text"]

y_test = test_data["label"]


vectorizer = TfidfVectorizer(stop_words="english", max_features=5000)


X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)


model = MultinomialNB()


model.fit(X_train_tfidf, y_train)


predictions = model.predict(X_test_tfidf)


accuracy = accuracy_score(y_test, predictions)


print("\nAccuracy:\n")

print(accuracy)


print("\nClassification Report:\n")

print(classification_report(y_test, predictions))


print("\nConfusion Matrix:\n")

print(confusion_matrix(y_test, predictions))


sample_reviews = [
    "This movie was absolutely fantastic and inspiring",
    "The film was boring and a complete waste of time"
]


sample_vectors = vectorizer.transform(sample_reviews)

sample_predictions = model.predict(sample_vectors)


print("\nSentiment Prediction:\n")


for review, prediction in zip(sample_reviews, sample_predictions):

    sentiment = "Positive" if prediction == 1 else "Negative"

    print(review, "->", sentiment)