# -*- coding: utf-8 -*-
"""ngram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

from collections import defaultdict, Counter
import math


text = "I love natural language processing and I love machine learning"


tokens = text.lower().split()


unigram_counts = Counter(tokens)

total_words = len(tokens)

vocab = set(tokens)

vocab_size = len(vocab)


print("Unigram Counts:\n")

for word, count in unigram_counts.items():
    print(word, ":", count)


print("\nUnigram Probabilities with Laplace Smoothing:\n")

for word in vocab:
    probability = (unigram_counts[word] + 1) / (total_words + vocab_size)
    print(word, ":", probability)


bigram_counts = defaultdict(Counter)

for i in range(len(tokens) - 1):
    current_word = tokens[i]
    next_word = tokens[i + 1]
    bigram_counts[current_word][next_word] += 1


print("\nBigram Counts:\n")

for word in bigram_counts:
    for next_word in bigram_counts[word]:
        print(f"({word}, {next_word}) : {bigram_counts[word][next_word]}")


print("\nBigram Probabilities with Laplace Smoothing:\n")

for word in bigram_counts:
    total_count = sum(bigram_counts[word].values())

    for next_word in vocab:
        probability = (bigram_counts[word][next_word] + 1) / (total_count + vocab_size)
        print(f"P({next_word} | {word}) = {probability}")