# -*- coding: utf-8 -*-
"""ngramprob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

from nltk.util import ngrams
from collections import Counter


corpus = """
this is my cat
this is my dog
my cat likes milk
my dog likes biscuits
"""


tokens = corpus.lower().split()


unigrams = list(ngrams(tokens, 1))
bigrams = list(ngrams(tokens, 2))
trigrams = list(ngrams(tokens, 3))


print("Unigrams:\n")

for unigram in unigrams:
    print(unigram)


print("\nBigrams:\n")

for bigram in bigrams:
    print(bigram)


print("\nTrigrams:\n")

for trigram in trigrams:
    print(trigram)


unigram_counts = Counter(unigrams)
bigram_counts = Counter(bigrams)


sentence = "this is my cat"

sentence_tokens = sentence.lower().split()


probability = 1


for i in range(len(sentence_tokens) - 1):
    first_word = sentence_tokens[i]
    second_word = sentence_tokens[i + 1]

    bigram = (first_word, second_word)
    unigram = (first_word,)

    bigram_count = bigram_counts[bigram]
    unigram_count = unigram_counts[unigram]

    probability *= bigram_count / unigram_count


print("\nProbability of sentence 'This is my cat':\n")

print(probability)