# -*- coding: utf-8 -*-
"""pos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('omw-1.4')


text = "The striped bats are hanging on their feet for best"


words = word_tokenize(text)


pos_tags = nltk.pos_tag(words)

print("Parts of Speech Tagging:\n")

for word, tag in pos_tags:
    print(word, ":", tag)


lemmatizer = WordNetLemmatizer()


lemmatized_words = [lemmatizer.lemmatize(word) for word in words]

print("\nLemmatization:\n")

for word in lemmatized_words:
    print(word)