# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import re


text = """
Rahul Sharma contacted support using rahul.sharma@gmail.com on 12/08/2025.
You can also reach Priya at priya_123@yahoo.in or office.mail@company.org.

Random numbers:
12345
998877
9876543210
9123456780
7800123456

Invalid contacts:
abc@com
user#mail.com
123456789
98765432101

More details:
Aman: aman.verma@outlook.com
Mobile: 8899776655
"""


email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

mobile_pattern = r'\b[6-9]\d{9}\b'


emails = re.findall(email_pattern, text)

mobile_numbers = re.findall(mobile_pattern, text)


print("Extracted Email Addresses:\n")

for email in emails:
    print(email)


print("\nExtracted Indian Mobile Numbers:\n")

for number in mobile_numbers:
    print(number)