# -*- coding: utf-8 -*-
"""rupars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import nltk
from nltk import CFG
from nltk.parse import RecursiveDescentParser
from nltk.parse import ShiftReduceParser
from nltk.parse.chart import ChartParser


grammar = CFG.fromstring("""

S -> NP VP
NP -> Det N | 'John'
VP -> V NP | V
Det -> 'the' | 'a'
N -> 'cat' | 'dog'
V -> 'chased' | 'slept'

""")


sentence = "John chased the dog".split()


print("Sentence:\n")

print(sentence)


print("\nTop-Down Parsing:\n")

top_down_parser = RecursiveDescentParser(grammar)

for tree in top_down_parser.parse(sentence):
    print(tree)


print("\nBottom-Up Parsing:\n")

bottom_up_parser = ShiftReduceParser(grammar)

for tree in bottom_up_parser.parse(sentence):
    print(tree)


print("\nCYK Parsing:\n")

cyk_parser = ChartParser(grammar)

for tree in cyk_parser.parse(sentence):
    print(tree)


print("\nComparison of Parsing Algorithms:\n")

print("1. Top-Down Parsing")
print("   - Starts from the start symbol")
print("   - Expands grammar rules recursively")
print("   - Easy to understand")
print("   - Inefficient for ambiguous grammars")


print("\n2. Bottom-Up Parsing")
print("   - Starts from input words")
print("   - Reduces words into grammar symbols")
print("   - More practical than top-down parsing")
print("   - May face shift-reduce conflicts")


print("\n3. CYK Parsing")
print("   - Dynamic programming based parser")
print("   - Efficient for context free grammars in CNF")
print("   - Handles ambiguity better")
print("   - Requires grammar conversion into CNF")