# -*- coding: utf-8 -*-
"""sentanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1VvQh8kUW8WlFTDQMIWTwEloBAsfTar
"""

import nltk
from nltk.sentiment import SentimentIntensityAnalyzer


nltk.download('vader_lexicon')


sia = SentimentIntensityAnalyzer()


texts = [
    "I absolutely loved this movie. It was fantastic and inspiring.",
    "The product is terrible and completely useless.",
    "The experience was okay, not too bad but not great either.",
    "I am very happy with the service provided.",
    "This is the worst application I have ever used."
]


for text in texts:

    scores = sia.polarity_scores(text)

    compound_score = scores["compound"]

    if compound_score >= 0.05:
        sentiment = "Positive"

    elif compound_score <= -0.05:
        sentiment = "Negative"

    else:
        sentiment = "Neutral"


    print("\nText:\n")

    print(text)

    print("\nSentiment Scores:\n")

    print(scores)

    print("\nPredicted Sentiment:\n")

    print(sentiment)