# -*- coding: utf-8 -*-
"""tf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import nltk
from nltk.corpus import stopwords
from collections import Counter
import math


nltk.download('punkt')
nltk.download('stopwords')


documents = [
    "Natural language processing is a branch of artificial intelligence",
    "Machine learning and artificial intelligence are transforming technology",
    "Natural language processing helps computers understand human language",
    "Artificial intelligence and machine learning are widely used today"
]


stop_words = set(stopwords.words('english'))


all_words = []

for doc in documents:
    tokens = nltk.word_tokenize(doc.lower())
    filtered = [word for word in tokens if word in stop_words]
    all_words.extend(filtered)


stopword_frequency = Counter(all_words)


print("Stopword Frequencies:\n")

for word, count in stopword_frequency.items():
    print(word, ":", count)


print("\nMost Frequent Stopwords:\n")

most_common = stopword_frequency.most_common(5)

for word, count in most_common:
    print(word, ":", count)


query = "artificial intelligence language"


query_terms = query.lower().split()


print("\nTF Values:\n")

for doc_number, doc in enumerate(documents, start=1):

    tokens = nltk.word_tokenize(doc.lower())

    total_terms = len(tokens)

    print("\nDocument", doc_number)

    for term in query_terms:

        tf = tokens.count(term) / total_terms

        print(term, ":", tf)


print("\nIDF Values:\n")

total_documents = len(documents)


for term in query_terms:

    document_frequency = 0

    for doc in documents:

        tokens = nltk.word_tokenize(doc.lower())

        if term in tokens:
            document_frequency += 1

    idf = math.log(total_documents / (1 + document_frequency))

    print(term, ":", idf)