# -*- coding: utf-8 -*-
"""tfcosine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


documents = [
    "Natural language processing is an important field of artificial intelligence",
    "Machine learning and artificial intelligence are closely related",
    "Natural language processing helps machines understand human language",
    "Deep learning is widely used in artificial intelligence"
]


vectorizer = TfidfVectorizer()


tfidf_matrix = vectorizer.fit_transform(documents)


print("TF-IDF Feature Names:\n")

print(vectorizer.get_feature_names_out())


print("\nTF-IDF Matrix:\n")

print(tfidf_matrix.toarray())


cosine_sim = cosine_similarity(tfidf_matrix)


print("\nCosine Similarity Matrix:\n")

print(cosine_sim)