# -*- coding: utf-8 -*-
"""transitionparsingrule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

class TransitionBasedParser:

    def __init__(self, sentence):
        self.stack = ["ROOT"]
        self.buffer = sentence[:]
        self.dependencies = []


    def shift(self):

        if self.buffer:
            self.stack.append(self.buffer.pop(0))


    def left_arc(self, relation):

        if len(self.stack) > 1:

            head = self.stack[-1]
            dependent = self.stack[-2]

            self.dependencies.append((head, relation, dependent))

            self.stack.pop(-2)


    def right_arc(self, relation):

        if len(self.stack) > 1:

            head = self.stack[-2]
            dependent = self.stack[-1]

            self.dependencies.append((head, relation, dependent))

            self.stack.pop()


    def show_state(self):

        print("Stack      :", self.stack)
        print("Buffer     :", self.buffer)
        print("Dependencies:", self.dependencies)
        print()


sentence = "I enjoy learning NLP".split()


parser = TransitionBasedParser(sentence)


print("Initial Configuration:\n")

parser.show_state()


parser.shift()

print("After SHIFT:\n")

parser.show_state()


parser.shift()

print("After SHIFT:\n")

parser.show_state()


parser.left_arc("nsubj")

print("After LEFT ARC:\n")

parser.show_state()


parser.shift()

print("After SHIFT:\n")

parser.show_state()


parser.shift()

print("After SHIFT:\n")

parser.show_state()


parser.right_arc("dobj")

print("After RIGHT ARC:\n")

parser.show_state()


parser.right_arc("xcomp")

print("After RIGHT ARC:\n")

parser.show_state()


print("Final Dependency Relations:\n")

for dependency in parser.dependencies:
    print(dependency)