# -*- coding: utf-8 -*-
"""trdepars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

import sys
!{sys.executable} -m pip install graphviz

!apt-get update
!apt-get install -y graphviz

class TransitionParser:

    def __init__(self, sentence):
        self.stack = []
        self.buffer = sentence[:]
        self.dependencies = []


    def shift(self):
        if self.buffer:
            self.stack.append(self.buffer.pop(0))


    def left_arc(self, relation):
        if len(self.stack) >= 2:
            dependent = self.stack[-2]
            head = self.stack[-1]

            self.dependencies.append((head, relation, dependent))

            self.stack.pop(-2)


    def right_arc(self, relation):
        if len(self.stack) >= 2:
            head = self.stack[-2]
            dependent = self.stack[-1]

            self.dependencies.append((head, relation, dependent))

            self.stack.pop()


    def print_state(self):
        print("Stack :", self.stack)
        print("Buffer:", self.buffer)
        print("Dependencies:", self.dependencies)
        print()


sentence = "I love NLP".split()


parser = TransitionParser(sentence)


print("Initial State:\n")

parser.print_state()


parser.shift()

print("After SHIFT:\n")

parser.print_state()


parser.shift()

print("After SHIFT:\n")

parser.print_state()


parser.left_arc("nsubj")

print("After LEFT-ARC:\n")

parser.print_state()


parser.shift()

print("After SHIFT:\n")

parser.print_state()


parser.right_arc("obj")

print("After RIGHT-ARC:\n")

parser.print_state()


print("Final Dependency Relations:\n")

for dependency in parser.dependencies:
    print(dependency)