# -*- coding: utf-8 -*-
"""word2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI19sMBi0uD03Rjb9y4b58jlXJcMDeC2
"""

!pip install gensim
import nltk
import matplotlib.pyplot as plt
from gensim.models import Word2Vec
from sklearn.decomposition import PCA

nltk.download('punkt')

sentences = [
    "Natural language processing is interesting",
    "Machine learning is a part of artificial intelligence",
    "Word embeddings capture semantic meaning",
    "Deep learning and neural networks are powerful",
    "Artificial intelligence is transforming technology"
]

tokenized_sentences = [nltk.word_tokenize(sentence.lower()) for sentence in sentences]

model = Word2Vec(
    sentences=tokenized_sentences,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

words = list(model.wv.index_to_key)

word_vectors = [model.wv[word] for word in words]

pca = PCA(n_components=2)

result = pca.fit_transform(word_vectors)

print("Word Vectors:\n")

for word in words:
    print(word, ":", model.wv[word][:5])


plt.figure(figsize=(10, 8))


for i, word in enumerate(words):

    plt.scatter(result[i, 0], result[i, 1])

    plt.text(result[i, 0], result[i, 1], word)


plt.title("Word2Vec Embedding Visualization using PCA")

plt.xlabel("PCA Component 1")

plt.ylabel("PCA Component 2")

plt.show()